version: '3.1'

services:
  dynamo-admin:
    build:
      dockerfile: Dockerfile-ddb-admin
      context: .
    environment:
      DYNAMO_ENDPOINT: localstack:4566
      AWS_REGION: us-west-1
    ports:
      - '8001:8001'
    depends_on:
      - localstack
    links:
      - localstack

  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_ACCESS_KEY=ABC
      - EDGE_PORT=4566
      - DEBUG=true
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - SERVICES=lambda,s3,cloudformation,sts,dynamodb
      - START_WEB=1
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=${TEMPDIR:-/tmp/localstack}
    ports:
      - '4566-4597:4566-4597'
      - '8080:8080'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"